// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetEmotionsApp.Data;

#nullable disable

namespace PetEmotionsApp.Migrations
{
    [DbContext(typeof(PetEmotionsAppContext))]
    partial class PetEmotionsAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("PetEmotionsApp.Models.FileUpload", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("FileContent")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("emotion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("fileDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FileUpload");
                });
#pragma warning restore 612, 618
        }
    }
}
